### PR TITLE
fix: move to a modern EIP-712 structs module

### LINKED ISSUE #3: Building wheel for bitarray (pyproject.toml) did not run successfully
`pip install zksync2`

There is a problem after using the command, which cannot be solved
Whether I install **_Visual Studio_** or download the local installation **_bitarray-2.5.1-cp38-cp38-win_amd64. whl_** in advance, it is the same error
**My python version is 3.8. How to solve this problem**

————————

> Building wheels for collected packages: bitarray, pysha3
>   Building wheel for bitarray (pyproject.toml) ... error
>   error: subprocess-exited-with-error
> 
>   × Building wheel for bitarray (pyproject.toml) did not run successfully.
>   │ exit code: 1
>   ╰─> [1 lines of output]
>       error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
>       [end of output]
> 
>   note: This error originates from a subprocess, and is likely not a problem with pip.
>   ERROR: Failed building wheel for bitarray
>   Building wheel for pysha3 (pyproject.toml) ... error
>   error: subprocess-exited-with-error
> 
>   × Building wheel for pysha3 (pyproject.toml) did not run successfully.
>   │ exit code: 1
>   ╰─> [9 lines of output]
>       running bdist_wheel
>       running build
>       running build_py
>       creating build
>       creating build\lib.win-amd64-cpython-38
>       copying sha3.py -> build\lib.win-amd64-cpython-38
>       running build_ext
>       building '_pysha3' extension
>       error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
>       [end of output]
> 
>   note: This error originates from a subprocess, and is likely not a problem with pip.
>   ERROR: Failed building wheel for pysha3
> Failed to build bitarray pysha3
> ERROR: Could not build wheels for bitarray, pysha3, which is required to install pyproject.toml-based projects

### LINKED ISSUE #43: pysha3 conflict
When I installing, I always get this error:ERROR: Could not build wheels for pysha3, which is required to install pyproject.toml-based projects

I tried install pysha3 manually, but also get this error. Also I have created a empty pyproject.toml - nothing

### PR DESCRIPTION
**Pull request by BoboTiG**
# What :computer: 
* changed the EIP-712 module to a [newer one](https://pypi.org/project/eip712-structs-ng/)

# Why :hand:
* fixes #3
* fixes #43

# Notes :memo:

The API does not change, it is a **drop-in replacement**, and as a bonus it unlocks Python 3.11 & 3.12 support.

### CODE REVIEW

**Comment by BoboTiG** [comment]
I updated the version + fixed the commit checker.

**Comment by BoboTiG** [comment]
Fixed the conflict 👍🏻

**Comment by petarTxFusion** [comment]
Thank you for your efforts. We will have to reject this PR since we are trying to move away from this dependency.

**Comment by BoboTiG** [comment]
Noted 👍🏻

**Pull request closed without merging**
