### PR TITLE
feat: add type annotations to zksync module

### PR DESCRIPTION
**Pull request by comilao**
# What :computer: 
* This PR intends to add type annotations to the `zksync` module
* Fixes `Running Tests` section in `README.md` based on this [workflow](https://github.com/zksync-sdk/zksync2-python/blob/master/.github/workflows/test.yml#L36)

# Why :hand:
* As mentioned in this [issue](https://github.com/ethereum/web3.py/issues/2781), adding an external module by `attach_modules` does not provide type annotations

# Evidence :camera:
Before this change, hovering over `zksync`, it shows 
zksync_Any
After this change, hovering over `zksync`, it shows
zksync_Zksync
This provides useful function hints in the code editor
useful_function_hints

# Notes :memo:
* Any notes/thoughts that the reviewers should know prior to reviewing the code?
- It's my first PR to the open-source world ever, please be patient with me if I did something wrong. Thank you in advance 🙏

### CODE REVIEW

**Comment by petarTxFusion** [comment]
Could you update this branch with latests changes so that test can pass? Thank you for your contributions

**Comment by comilao** [comment]
> Could you update this branch with latests changes so that test can pass? Thank you for your contributions

Sorry about this.
Actually I am thinking of a big refactor plan.
- `isort` to sort imports
- `flake8` linter to the code base
- `black` for formatting
- `mypy` for type hints

All of the above can be put inside `pre-commit` hook config file. We can update the `CONTRIBUTING.md` to ask contributors to install it and also add these checks it to the `validate.yml` GitHub Actions. How do you think about it?

**Comment by petarTxFusion** [comment]
We are planing to refactor large part of the code in the near future which will resolve typing issues, we are trying to avoid other dependencies as much as possible plan is to use native typing. The main problem lies in the design itself. We are planning to go with `External Modules` and `Custom Providers` you can read more about it [here](https://snakecharmers.ethereum.org/web3-py-patterns-customizations/)

**Comment by comilao** [comment]
Thanks a lot for this comment. Glad to know your team will be revamping this repo, it really helps me a lot during my work. I have made another PR #68  to explain more about what I mean, sorry for the inconsiderate comments earlier, I can also help with some tasks if you needed help. I will also close this PR first.
(BTW, I'm a QA automation engineer, so if you need, I can help with writing more test cases)

**Pull request closed without merging**
